before_script:
  - ./development-setup.sh

minimal:
  script:
    - make test-minimal

# Docker Debian

minimal-debian-jessie:
  image: debian:jessie
  script:
    - make test-minimal

minimal-debian-latest:
  image: debian:latest
  script:
    - make test-minimal

minimal-debian-testing:
  image: debian:testing
  script:
    - make test-minimal

minimal-debian-unstable:
  image: debian:unstable
  script:
    - make test-minimal

# Docker Ubuntu

minimal-ubuntu-trusty:
  image: ubuntu:trusty
  script:
    - make test-minimal

minimal-ubuntu-wily:
  image: ubuntu:wily
  script:
    - make test-minimal

minimal-ubuntu-latest:
  image: ubuntu:latest
  script:
    - make test-minimal

# Docker openSUSE

minimal-opensuse-latest:
  image: opensuse:latest
  script:
    - make test-minimal

minimal-opensuse-tumbleweed:
  image: opensuse:tumbleweed
  script:
    - make test-minimal
